name: Android CI

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease --stacktrace
     
    - name: Prepare App
      run: 
          mkdir -p ${{ github.workspace }}/apk/*.apk
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: Mtvbox
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/apk/app-debug.apk
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file:  app/build/outputs/apk/release/*.apk
        tag: ${{ github.ref }}
        release_name: ${{ github.ref }}
        overwrite: true
        file_glob: true
        body: ""
